### ISSUE TITLE
ValueError: 'a' cannot be empty unless no samples are taken

### ISSUE THREAD

**Issue by KalyanBanik** [zhykoties/DeepAR#8]
for different train test split dataset I am getting this error

```
Traceback (most recent call last):

  File "<ipython-input-4-6b0715d9506b>", line 6, in <module>
    args.restore_file)

  File "<ipython-input-1-a393da520de1>", line 121, in train_and_evaluate
    test_loader, params, epoch)

  File "<ipython-input-1-a393da520de1>", line 83, in train
    test_metrics = evaluate(model, loss_fn, test_loader, params, epoch, sample=args.sampling)

  File "/Users/kalyan.admin/KalyanWork/Timeseries_covid/evaluate.py", line 95, in evaluate
    random_sample_10 = np.random.choice(top_10_nd_sample, size=10, replace=True)

  File "mtrand.pyx", line 773, in numpy.random.mtrand.RandomState.choice
```
the implementation worked well. But right now I am  getting it  for several train test splitting. what will be the solution

**Comment by zhykoties** [comment]
Check the shape for top_10_nd_sample?
